CREATE TABLE IF NOT EXISTS users (
 id BIGSERIAL PRIMARY KEY,
 name TEXT NOT NULL,
 mobile TEXT UNIQUE NOT NULL,
 email TEXT UNIQUE NOT NULL,
 password_hash TEXT NOT NULL,
 referral_code TEXT UNIQUE NOT NULL,
 referred_by BIGINT REFERENCES users(id),
 coins BIGINT NOT NULL DEFAULT 1000 CHECK (coins >= 0),
 status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','BLOCKED')),
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 last_seen TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS rounds (
 period TEXT PRIMARY KEY,
 number INT NOT NULL CHECK(number BETWEEN 0 AND 9),
 colour TEXT NOT NULL,
 size TEXT NOT NULL,
 source TEXT NOT NULL DEFAULT 'AUTO',
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS bets (
 id BIGSERIAL PRIMARY KEY,
 user_id BIGINT NOT NULL REFERENCES users(id),
 period TEXT NOT NULL REFERENCES rounds(period),
 amount BIGINT NOT NULL CHECK(amount > 0),
 choice TEXT NOT NULL,
 result TEXT,
 outcome TEXT CHECK(outcome IN ('WIN','LOSS','PENDING')),
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS transactions (
 id BIGSERIAL PRIMARY KEY,
 user_id BIGINT NOT NULL REFERENCES users(id),
 type TEXT NOT NULL CHECK(type IN ('DEPOSIT','WITHDRAWAL','BET','WIN','REFUND','REFERRAL')),
 amount BIGINT NOT NULL,
 status TEXT NOT NULL,
 reference TEXT,
 meta JSONB NOT NULL DEFAULT '{}'::jsonb,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS requests (
 id BIGSERIAL PRIMARY KEY,
 user_id BIGINT NOT NULL REFERENCES users(id),
 type TEXT NOT NULL CHECK(type IN ('DEPOSIT','WITHDRAWAL')),
 amount BIGINT NOT NULL CHECK(amount > 0),
 status TEXT NOT NULL DEFAULT 'PENDING' CHECK(status IN ('PENDING','APPROVED','REJECTED')),
 details JSONB NOT NULL DEFAULT '{}'::jsonb,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 reviewed_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS activities (
 id BIGSERIAL PRIMARY KEY,
 user_id BIGINT REFERENCES users(id),
 action TEXT NOT NULL,
 details TEXT,
 coins BIGINT,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS support_tickets (
 id BIGSERIAL PRIMARY KEY,
 user_id BIGINT NOT NULL REFERENCES users(id),
 message TEXT NOT NULL,
 status TEXT NOT NULL DEFAULT 'OPEN',
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 resolved_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_requests_status ON requests(status);
CREATE INDEX IF NOT EXISTS idx_activities_created ON activities(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_transactions_user ON transactions(user_id, created_at DESC);
